name: SinglePlayerSleep
version: 1.1.0
main: com.mrsuffix.singleplayersleep.SinglePlayerSleep
api-version: 1.20
author: MRsuffixx
description: A modern plugin that allows night to pass when only one player sleeps
website: https://github.com/MRsuffixx/SinglePlayerSleep

commands:
  sleep:
    description: Main command for SinglePlayerSleep
    usage: /<command> [subcommand]
    permission: singleplayersleep.use
    aliases: [sps, nightskip]

permissions:
  singleplayersleep.*:
    description: All SinglePlayerSleep permissions
    children:
      singleplayersleep.use: true
      singleplayersleep.skip: true
      singleplayersleep.stats: true
      singleplayersleep.reload: true
      singleplayersleep.debug: true
      singleplayersleep.cooldown: true
    default: op

  singleplayersleep.use:
    description: Basic plugin usage
    default: true

  singleplayersleep.skip:
    description: Manually skip night
    default: op

  singleplayersleep.stats:
    description: View sleep statistics
    default: op

  singleplayersleep.reload:
    description: Reload plugin configuration
    default: op

  singleplayersleep.debug:
    description: Toggle debug mode
    default: op

  singleplayersleep.cooldown:
    description: Manage sleep cooldowns
    default: op

depend: []
softdepend: []
